package.json
yarn.lock

Fix an issue where the deployed service does not have access to the data/ files, since they're outside the `dist` directory.
This PR changes the issue by copying the files inside `dist` after building

fix: fix missing json data files on build

---

README.md
src/api.ts
src/index.ts
src/webhook.ts
test/e2e/__snapshots__/moderationList.test.ts.snap
test/e2e/moderationList.test.ts

Reorganize API endpoints, for a consistent naming and path for all endpoints.
This service is getting more and more diverse features:
- #5 
- #9 
- #12 
- #15 
Reorganizing now to lay the ground
The /webhook has been isolated, as it'll be shared by all other futures update.

fix: reorganize endpoints

---

README.md
src/api.ts
test/e2e/__snapshots__/moderation.test.ts.snap
test/e2e/moderation.test.ts

Getting rid of case sensitive routes:
Rename the route /moderationList to /moderation, and ?fields params to be ?list

fix: rename /moderationList to /moderation

---

src/api.ts
src/lib/nftClaimer.ts
test/e2e/nftClaimer.test.ts

Return signature as a json, with `r`, `s` and `v` keys, instead of string, for easier consumption by smart contract

fix: return signature in r,s,v format

---

src/lib/votesReport.ts

In the CSV votes report, new line characters in `reason` field are interpreted as is, and it does insert a new line in the CSV file, breaking the CSV format.
Fix #46 
New lines should be ignored
- Add a regex to strip all new lines characters from `reason` field
- Go to https://snapshot-lwxw3n2hm-snapshot.vercel.app/#/stgdao.eth/proposal/0x6b703b90d3cd1f82f7c176fc2e566a2bb79e8eb6618a568b52a4f29cb2f8d57b (this votes contains many reason with new lines characters)
- Download the CSV votes report
- There should be no blanks lines in the report

fix: ignore new line characters in reason

---

package.json

The `public` directory is not included in `dist` on `yarn build`. 
Add the dir in the dist output
- Copy `public` to `dist` when building the app
- Run `yarn build`
- `public` directory should appear in `dist`

fix: fix missing public directory in dist

---

src/webhook.ts

Header keyname for checking the webhook authentication key is incorrect
Change the header keyname to the correct one
- Rename key from `authenticate` to `Authentication`
- Nothing

fix: fix incorrect webhook auth header

---

src/lib/storage/aws.ts

We're using fetch directly to get a cached file from AWS, and do not check for cache existence first. Any error returned while fetching the file is considered as cache not existing, and will continue to cache creation
`get` should not raise an error, and should only return `false` when the cache file does not exist (like in the `File` cache engine)
When the `get` command from AWS fail with a 404 error, just return `false`, and do not raise an error. (Do not pollute the logs)
- Add check to not log the error on cache file fetching failure, when cache do not exist
- Try to trigger a votes CSV file creation, for a proposal ID not existing on AWS yet
- It should not console.error the error

fix: do not throw an error when cached file does not exist

---

src/index.ts

We track user IP in the [http] logs. Snapshot moto is not to track user related data
Remove IP from logs
- Remove IP from the http logs
- Run `yarn dev`
- Open some URL
- In the logs, it should show the request, without the IP

chore: remove IP tracking from logs

---

src/index.ts

Error caught and throw by the app are formatted using JSON RPC.
Express default 404 error (for non-existing routes) are formatted using HTML.
Currently, 404 errors are returned in both JSON RPC and HTML format. Errors response should always use the same format, for consistency, and avoid parsing error from caller.
Default 404 Error responses from express should follow the JSON RPC format, like the rest of the endpoint.
- Add catch-all routes, to always return the page not found error using JSON RPC
- Visit `localhost:3005/test`
- It should return a 404 error, JSON RPC formatted

fix: return 404 JSON RPC error

---

package.json
yarn.lock

Jest tests are failing due to last version of snapshot.js
Downgrade the version of snapshot.js used
- Downgrade snapshot.js to `0.4.97`
- Run `yarn test`
- They should not complain about async task not completed
- They should complete and succeed on Github actions

chore: downgrade dependencies causing tests to fail

---

src/helpers/sentry.ts

Sentry is always enabled, as long as DSN is set, and may send errors when developing on local.
- Enable sentry logger only on production
- Add a condition to enable sentry only on prod, by checking `NODE_ENV`
- `NODE_ENV` have been set to `production` on the prod server
- N/A

chore: enable sentry only on prod

---

README.md
src/helpers/utils.ts
src/lib/votesReport.ts
test/unit/lib/votesReport.test.ts

There's currently different error codes for different type of errors, such as `PROPOSAL_NOT_FOUND` and `PROPOSAL_NOT_CLOSED`.
API endpoint has evolved such that we do not return these errors anymore, and prefer to return a generic 404 error.
- Removed unused error codes
- Remove `PROPOSAL_NOT_FOUND` and `PROPOSAL_NOT_CLOSED` error code, and always use generic `RECORD_NOT_FOUND` for record not found error.

chore: remove errors granularity

---

src/lib/moderationList.ts
test/e2e/__snapshots__/moderation.test.ts.snap
test/fixtures/moderation.ts
test/unit/lib/__snapshots__/moderationList.test.ts.snap

Moderation list endpoint is not returning the list of flagged IPs
This is follow-up of https://github.com/snapshot-labs/laser/pull/1
- Return the list of flagged IPs
- Add support for returning the list of flagged Ips
- Add a flagged IP in your database 
- Poll the `/api/moderation` endpoint 
- It should return the flagged IP from your database

feat: add flagged IPs to moderation list

---

src/lib/metrics/digitalOcean.ts
src/lib/metrics/index.ts

When API key is not set, it should fail silently, as missing API key also means that feature is disabled.

fix: mute error when the digital ocean API key is missing

---

.github/dependabot.yml
src/index.ts
src/lib/metrics/index.ts
src/lib/queue.ts

- whitelist endpoints for http metrics, currently getting a lot of spam, skewing the results
- normalize metrics path, so /votes/1 and /votes/2 are counted together
- add queue process time to metrics
- remove powered by express header
- remove dependabot

chore: whitelist http request from metrics

---

package.json

There's dependency leftover, from metrics, when the package was migrated to @snapshot-labs/snapshot-metrics. Old dependency were not removed cleanly
- Remove old unused dependency, obsolete now that we've migrated to @snapshot-labs/snapshot-metrics
- Remove `express-prom-bundle` and `prom-client` dependency, which were now moved to `@snapshot-labs/snapshot-metrics`
- N/A

chore: removed unused dependency

---

package.json
src/index.ts
yarn.lock

this output to the logs is now obsolete, since the introduction of the dashboard.
Remove verbose logs, to decrease noise in the logs.

chore: remove morgan output

---

package.json
yarn.lock

This PR remove the unused `@types/serve-favicon` dependency

chore: remove unused dependency

---

package.json
src/helpers/snapshot.ts
src/helpers/utils.ts
src/lib/metrics/digitalOcean.ts
src/lib/nftClaimer/utils.ts
src/sentryTunnel.ts
test/integration/helpers/utils.test.ts
yarn.lock

There's a lot of recurring connections to the same services, at a high rate. 
- Sentry via SentryTunnel
- Snapshot-hub via the votes CSV generation
Opening a new connection on each request is costly, and create overhead, particularly on frequently requested url
We should reuse the connection when possible, by using a keep alive connection.
Fix #167 
Fix #168
Fix SNAPSHOT-SIDEKICK-2
Fix SNAPSHOT-SIDEKICK-E
- Use `node-fetch` instead of `cross-fetch` (don't need browser support)
- Add a wrapper function to `node-fetch`, injecting keep-alive connection by using a custom agent.
- Use that custom `fetch` function whenever possible
- Run `yarn test:integration`
- Not sure if HTTP interceptor can detect the keep-alive header correctly, but you can also try intercepting a request, such as ` curl …

feat: use keep alive connections

---

src/lib/metrics/index.ts

This PR enable the mysql connection instrumentation, enabled by sentry-metrics v1.2.0

chore: enable DB instrumentation

---

src/helpers/snapshot.ts
src/lib/nftClaimer/mint.ts
src/lib/nftClaimer/utils.ts
test/integration/lib/nftClaimer/utils.test.ts
test/unit/lib/nftClaimer/mint.test.ts

First part of the following pitch: https://www.notion.so/snapshotlabs/NFT-claimer-minting-constrains-de9705b71aca4b1aa57ff62b47d1824a
- Restrict mint only to voter
- Add related tests
- Run a local instance of this branch (Copy and set the missing env var from /test/.env.test)
- Run a local instance of snapshot https://github.com/snapshot-labs/snapshot/pull/3885 (set the `VITE_SIDEKICK_URL` in .env to your local sidekick instance)
- On a proposal you have not voted yet, if you try to mint, it should return an error
- On a proposal you have voted, if you try to mint, it should mint
As of now, the UI only return "Invalid data submitted" message on error. UI needs some refactoring to check if user already voted, and show am error another message, instead of starting the mint and failing from …

fix: restrict NFT minting only to voter

---

README.md
src/lib/moderationList.ts
test/e2e/__snapshots__/moderation.test.ts.snap
test/e2e/moderation.test.ts
test/fixtures/moderation.ts
test/unit/lib/__snapshots__/moderationList.test.ts.snap
test/unit/lib/moderationList.test.ts

The moderation data for space and proposals have been moved from laser DB to hub DB. Getting those data from laser is now obsolete.
- Remove verified/flagged spaces and flagged proposals data from the moderation endpoint. 
- Run `yarn dev`
- Open `localhost:3005/api/moderation`
- It should not return data for verified/flagged spaces and flagged proposals anymore
DO NOT MERGE YET

fix: remove flagged/verified proposals/spaces

---

README.md
src/index.ts
src/lib/cache.ts
src/lib/cacheRefresher.ts
src/lib/votesReport.ts

Votes CSV reports are available only for closed proposals
Enable CSV reports for active proposals (requested by some specific users). 
Reports will be cached, and refreshed every 15 min in the background.
- Enable CSV reports for active proposals
- Add cache refresher task to auto refresh cache every X min
- Save the list of partial cached proposals ID in a file (stored on AWS), to track which ID to refresh, until proposal is closed.
in lib/cacheRefresher.ts, edit `REFRESH_INTERVAL` to something like 30s
- Run `yarn dev`
- Run `curl -X POST localhost:3005/api/votes/ID` (replace ID with an active propopsal ID)
- It should return a 202 code if not cached yet (cache creation will be triggered in the background)
- It should return the csv content when cached
- Monitor the `yarn dev` console, …

feat: allow partial CSV votes reports for active proposals

---

README.md
src/lib/moderationList.ts
test/e2e/__snapshots__/moderation.test.ts.snap
test/fixtures/moderation.ts
test/unit/lib/__snapshots__/moderationList.test.ts.snap

Removing unused flagged proposals title and body keywords

fix: remove unused flagged proposals keywords from moderation

---

src/lib/metrics/index.ts

Instrument the response time and code from Brovider networks
Will return metrics like
```
provider_response_code{network="97"} 200
provider_response_code{network="137"} 200
provider_response_code{network="204"} 200
provider_response_code{network="1"} 200
provider_response_code{network="108"} 200
provider_duration_seconds{network="97",status="1"} 0.512035792
provider_duration_seconds{network="137",status="1"} 0.541225708
provider_duration_seconds{network="204",status="1"} 0.561804417
provider_duration_seconds{network="1",status="1"} 0.58473075
provider_duration_seconds{network="108",status="1"} 0.581856208
```
Those metrics will make the dashboard act as Brovider RPC node monitoring (response time, full archive node availability), and wil raise alert on some events (slow node, node down, …

chore: instrument Brovider calls

---

package.json
src/lib/storage/file.ts
test/e2e/votesReport.test.ts

Tests are stucked on some setup, due to `start-server-and-test` script waiting on wrong url.
Additonally, fix some edge case when test are failing due to non-existing folder on CI
Pass the full absolute url instead of just the port to `start-server-and-test`
- Run `yarn test`
- Test should run
- Test should pass on CI

chore: fix tests stucked waiting on wrong url

---

package.json
src/api.ts
src/helpers/snapshot.ts
src/lib/ai.ts
src/lib/ai/summary.ts
test/.env.test
yarn.lock

Adds an OpenAI generated summary (300 characters long) endpoint with the route `/api/ai/summary`.
Requires a new env var `OPENAI_API_KEY` to be set.

feat: add AI summary

---

test/e2e/votesReport.test.ts

Fix still failing tests, due to queue doing things async after test have ended.
This PR add a `sleep` to some tests, allowing more time for the queue to complete their task before shutting down the instance

chore: fix failing tests

---

src/lib/cache.ts
src/lib/metrics/index.ts

Instrument the cache engine
- Track number of hit/miss per type (votesReports, aiSummary, etc...)
- Send a curl request to any endpoint using a cache (e.g. `curl -X POST localhost:3005/api/votes/[PROPOSAL-ID]`)
- Go to http://localhost:3005/metrics
- You should see new metrics under
```
```

chore: instrument the cache engine

---

test/e2e/votesReport.test.ts

`parseInt(process.env.QUEUE_INTERVAL || '15e3')` will be actually `15`

fix: parseInt won't work with 15e3

---

src/lib/ai/textToSpeech.ts

Decrease the minimum required proposal body chars length to enable AI speech.

fix: decrease min body length for AI text to speech

---

src/helpers/snapshot.ts

Fix graphql query to match snapshot-hub updated schema introduced with https://github.com/snapshot-labs/snapshot-hub/pull/836

fix: fix graphql schema to match hub

---

test/e2e/nftClaimer.test.ts
test/unit/lib/nftClaimer/deploy.test.ts
test/unit/lib/nftClaimer/mint.test.ts
test/unit/lib/nftClaimer/utils.test.ts

Disable NFT Claimer tests, which were relying on Goerli network, which is now off.

chore: disable nft claimer tests

---

src/lib/queue.ts

Bot activities are being detected on the CSV votes endpoint, degrading service performance.
This PR introduces a cap on the number of concurrent CSV votes generation, so that even if 100 different CSV reports are being requested, only 10 are being processed at a given time

fix: cap concurrent queues processing items

---

src/api.ts
src/index.ts
src/lib/domain.ts

Working towards https://github.com/snapshot-labs/workflow/issues/142
See also https://discord.com/channels/955773041898573854/1282876175642918964/1283367668648382587
This PR will add a new `/api/domain` endpoint to return a custom domain associated to an offchain space.
Domains list will be pulled from the snapshot-spaces repo, be cached in memory, and refreshed every 5 minutes.
- `yarn dev`
- monitor console to confirm that the domain list has been loaded
- `curl http://localhost:3005/api/domains/vote.lends.so`
- it should return `{"domain":"vote.lends.so","space_id":"s:lendsdao.eth"}`
- `curl http://localhost:3005/api/domains/random`
- it should return `{"domain":"vote.lends.so","space_id":null}`

feat: add domain api to return custom domain associated to an offchain space

---

src/api.ts

This PR will remove the error logging for the proxy action
Proxy url can be anything, and is raising too much errors

fix: stop logging proxy errors

---

src/helpers/snapshot.ts
src/lib/metrics/index.ts

This PR will monitor only premium networks, instead of full list
most non-premium networks are not maintained properly, and are creating a lot of errors that will not be fixed, and consuming all the sentry quota
- Go to http://localhost:3005/metrics
- After a while, the list with `provider_response_code` should only contain premium networks

fix: monitor only premium networks
